name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:bienvenido 
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Bienvenido ¿En qué puedo ayudarte? contactame para mas informacion "
        pr-message: "http://T.me//Sandragustavo"
